### ISSUE TITLE
Not an issue, just a thanks

### ISSUE THREAD

**Issue by aswansyahputra** [onlyphantom/finhacks_bandung#1]
Hi Sam!

Thank you for sharing this. I did followed your session in Finhacks Bandung, such a great sharing you did there!

I really loved to collaborate with people working in R, look forward if I can collaborate with **algorit.ma** in near future.

Regards,
Aswan

*here are some of my projects and collaborative projects using Shiny:*
- [SenseHub: an integrated web application for sensory analyses](https://s.id/sensehub_basic)
- [MCDM: Multiple Criteria Decision Making](https://aswansyahputra.shinyapps.io/mcdm)
- [Thermostats: make your own hot stats](https://aswansyahputra.shinyapps.io/thermostats)

**Comment by onlyphantom** [comment]
@aswansyahputra sorry for overlooking this until now. I'm now working on a few new projects, including [this one](https://github.com/onlyphantom/pedagogy), working link at https://pedagogy.azurewebsites.net

I'll be speaking about the use of Shiny and Flask as well as a bunch of other stuffs in Bandung again in 2 weeks time. If you're in town, let's do coffee or breakfast before my session? Will love to see how we can work together. 

If you prefer, my email is at samuel@algorit.ma we can continue our discussion there. Looking forward to meet in person and thanks so much for the kind words!
